apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: STORAGE_CLASS_TYPE
provisioner: STORAGE_CLASS_PROVISIONER
parameters:
  type: STORAGE_CLASS_TYPE
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: k8s
  labels:
    prometheus: k8s
spec:
  replicas: 2
  version: PROMETHEUS_VERSION
  externalUrl: PROMETHEUS_EXTERNAL_URL
  serviceAccountName: prometheus-k8s
  serviceMonitorSelector:
    matchExpressions:
    - {key: k8s-app, operator: Exists}
  ruleSelector:
    matchLabels:
      role: alert-rules
      prometheus: k8s
  nodeSelector:
    node_label_key: node_label_value
  resources:
    requests:
      memory: PROMETHEUS_MEMORY_REQUEST
  retention: PROMETHEUS_STORAGE_RETENTION
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  storage:
    class: STORAGE_CLASS_TYPE
    selector:
    resources:
    volumeClaimTemplate:
      metadata:
        annotations:
          annotation1: prometheus
      spec:
        storageClassName: STORAGE_CLASS_TYPE
        resources:
          requests:
            storage: PROMETHEUS_STORAGE_VOLUME_SIZE
  alerting:
    alertmanagers:
    - namespace: CUSTOM_NAMESPACE
      name: alertmanager-main
      port: web
